---
version: '2.2'
services:
  development:
    image: ${IMAGE:-apicast-development:latest}
    depends_on:
      - redis
    working_dir: /opt/app-root/src/
    volumes:
      - .docker/lua_modules:/opt/app-root/src/lua_modules
      - .docker/local:/opt/app-root/src/local
      - .docker/vendor/cache:/opt/app-root/src/vendor/cache
      # no need to access those from docker
      - /opt/app-root/src/.docker
      - /opt/app-root/src/.git
    command: cat
    tty: true
    init: true
    environment:
      EDITOR: vi
      TEST_NGINX_REDIS_HOST: redis
      TEST_NGINX_BINARY: openresty
      PROJECT_PATH: /opt/app-root/src
      TEST_NGINX_APICAST_PATH: /opt/app-root/src/gateway
      ROVER: /usr/local/openresty/luajit/bin/rover
      HOME: /opt/app-root/src/
      # https://github.com/jenkinsci/docker/issues/519#issuecomment-313052325
      GIT_COMMITTER_NAME: ${GIT_COMMITTER_NAME:-${USER}}
      GIT_COMMITTER_EMAIL: ${GIT_COMMITTER_EMAIL:-""}
  redis:
    image: redis
