version: '2.1'
services:
  development:
    image: apicast-development
    user: root
    depends_on:
      - redis
    command: "bash"
    volumes:
      - .:/home/centos/
    environment:
      LOCAL_USER_ID: ${LOCAL_USER_ID}
      TEST_NGINX_REDIS_HOST: redis
      TEST_NGINX_BINARY: openresty
      PROJECT_PATH: /home/centos
      TEST_NGINX_APICAST_PATH: /home/centos/gateway
      ROVER: /usr/local/openresty/luajit/bin/rover
  redis:
    image: redis
