version: '2'
services:
  gateway:
    image: docker-gateway-test
    ports:
      - "8080:8080"
      - "8090:8090"
    env_file: .env
  test:
    image: docker-gateway-test
    depends_on:
      - gateway
    entrypoint: ""
    dns: 127.0.0.1
  prove:
    image: docker-gateway-test
    user: root
    environment:
      TEST_NGINX_BINARY: openresty
      TEST_NGINX_APICAST_PATH: /opt/app
    command: prove
    volumes:
            - ./t:/opt/app/t
