---
version: '3.8'
services:
  gateway:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
    - proxy
    - tls.termination
    - actual.upstream
    environment:
      THREESCALE_CONFIG_FILE: /tmp/config.json
      THREESCALE_DEPLOYMENT_ENV: staging
      APICAST_CONFIGURATION_LOADER: lazy
      APICAST_WORKERS: 1
      APICAST_LOG_LEVEL: debug
      APICAST_CONFIGURATION_CACHE: "0"
    expose:
      - "8080"
      - "8090"
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ./examples/forward-proxy/apicast-config.json:/tmp/config.json
  tls.termination:
    image: alpine/socat:1.7.4.4
    container_name: tls.termination
    command: "-v openssl-listen:443,reuseaddr,fork,cert=/etc/pki/tls.pem,verify=0,openssl-min-proto-version=TLS1.3,openssl-max-proto-version=TLS1.3 TCP:actual.upstream:80"
    expose:
      - "443"
    restart: unless-stopped
    volumes:
      - ./examples/forward-proxy/upstream-cert/upstream.pem:/etc/pki/tls.pem
  actual.upstream:
    image: kennethreitz/httpbin
  proxy:
    build:
      dockerfile: ./examples/forward-proxy/tinyproxy.Dockerfile
    expose:
      - "3128:3128"
      - "443:443"
    volumes:
      - ./examples/forward-proxy/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
