version: '2'
services:
  gateway:
    image: docker-gateway-test
    ports:
      - "8080:8080"
      - "8090:8090"
    env_file: .env
  test:
    image: docker-gateway-test
    depends_on:
      - gateway
    entrypoint: ""
    dns: 127.0.0.1
