---
version: '2.2'
services:
  development:
    image: ${IMAGE:-quay.io/3scale/apicast-ci:openresty-1.19.3-pr1379}
    platform: "linux/amd64"
    depends_on:
      - redis
    working_dir: /opt/app-root/src/
    command: cat
    tty: true
    init: true
    environment:
      EDITOR: vi
      TEST_NGINX_REDIS_HOST: redis
      TEST_NGINX_REDIS_MASTER: redismaster
      TEST_NGINX_REDIS_SENTINEL_1_HOST: sentinel-1
      TEST_NGINX_REDIS_SENTINEL_2_HOST: sentinel-2
      TEST_NGINX_REDIS_SENTINEL_3_HOST: sentinel-3
      TEST_NGINX_REDIS_SENTINEL_PORT: 5000
      TEST_NGINX_BINARY: openresty
      PROJECT_PATH: /opt/app-root/src
      TEST_NGINX_APICAST_PATH: /opt/app-root/src/gateway
      ROVER: /usr/local/openresty/luajit/bin/rover
      HOME: /opt/app-root/src/
      # https://github.com/jenkinsci/docker/issues/519#issuecomment-313052325
      GIT_COMMITTER_NAME: ${GIT_COMMITTER_NAME:-${USER}}
      GIT_COMMITTER_EMAIL: ${GIT_COMMITTER_EMAIL:-""}
  redis:
    image: redis
  redis-master:
    image: redis
  redis-slave-1:
    image: redis
    command: redis-server --slaveof redis-master 6379
  redis-slave-2:
    image: redis
    command: redis-server --slaveof redis-master 6379
  sentinel-1:
    build:
      context: ./redis-sentinel
    depends_on:
        - redis-master
        - redis-slave-1
        - redis-slave-2
  sentinel-2:
    build:
      context: ./redis-sentinel
    depends_on:
        - redis-master
        - redis-slave-1
        - redis-slave-2
  sentinel-3:
    build:
      context: ./redis-sentinel
    depends_on:
        - redis-master
        - redis-slave-1
        - redis-slave-2
