version: '2'
services:
  gateway:
    image: quay.io/3scale/apicast:v2
    depends_on:
      - redis
      - oauth
    ports:
      - "8080:8080"
      - "8090:8090"
    env_file: .env
  redis:
    image: redis
  oauth:
    build: ./auth-server
    image: auth-server
    ports:
      - "3000:3000"
    volumes:
      - ./auth-server:/opt/app/auth-server
  client:
    build: ./client
    image: client
    links:
      - gateway
      - oauth
    ports:
      - "3001:3001"
    volumes: 
      - ./client:/opt/app/client
